//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netretis.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class inputMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal inputMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("netretis.Resources.inputMessages", typeof(inputMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SocialWP.
        /// </summary>
        internal static string applicazione {
            get {
                return ResourceManager.GetString("applicazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tiinx.it/xFaster/xFasterGateWindowsPhone7.asmx.
        /// </summary>
        internal static string endPointIT {
            get {
                return ResourceManager.GetString("endPointIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:190/www.xFaster/xFasterGateWindowsPhone7.asmx.
        /// </summary>
        internal static string endPointLocal {
            get {
                return ResourceManager.GetString("endPointLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.tiinx.it/xFaster/xFasterGateWindowsPhone7.en.asmx.
        /// </summary>
        internal static string endPointUS {
            get {
                return ResourceManager.GetString("endPointUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.im.social.announce.insert.xml.
        /// </summary>
        internal static string im_social_announce_insert {
            get {
                return ResourceManager.GetString("im_social_announce_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.im.social.announcetype.list.xml.
        /// </summary>
        internal static string im_social_announcetype_list {
            get {
                return ResourceManager.GetString("im_social_announcetype_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.im.social.commenti.insert.xml.
        /// </summary>
        internal static string im_social_commenti_insert {
            get {
                return ResourceManager.GetString("im_social_commenti_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.im.social.commenti.list.xml.
        /// </summary>
        internal static string im_social_commenti_list {
            get {
                return ResourceManager.GetString("im_social_commenti_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.im.social.news.addrank.xml.
        /// </summary>
        internal static string im_social_news_addrank {
            get {
                return ResourceManager.GetString("im_social_news_addrank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.im.social.news.element.xml.
        /// </summary>
        internal static string im_social_news_element {
            get {
                return ResourceManager.GetString("im_social_news_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.im.social.news.element.tags.xml.
        /// </summary>
        internal static string im_social_news_element_tags {
            get {
                return ResourceManager.GetString("im_social_news_element_tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.im.social.news.insert.xml.
        /// </summary>
        internal static string im_social_news_insert {
            get {
                return ResourceManager.GetString("im_social_news_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.im.social.news.list.xml.
        /// </summary>
        internal static string im_social_news_list {
            get {
                return ResourceManager.GetString("im_social_news_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.im.social.news.list.byuser.xml.
        /// </summary>
        internal static string im_social_news_list_byuser {
            get {
                return ResourceManager.GetString("im_social_news_list_byuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.im.social.news.list.piu.letti.xml.
        /// </summary>
        internal static string im_social_news_list_piu_letti {
            get {
                return ResourceManager.GetString("im_social_news_list_piu_letti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.im.social.news.list.piu.votati.xml.
        /// </summary>
        internal static string im_social_news_list_piu_votati {
            get {
                return ResourceManager.GetString("im_social_news_list_piu_votati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.im.social.news.listbytag.xml.
        /// </summary>
        internal static string im_social_news_listbytag {
            get {
                return ResourceManager.GetString("im_social_news_listbytag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.im.social.news.update.xml.
        /// </summary>
        internal static string im_social_news_update {
            get {
                return ResourceManager.GetString("im_social_news_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.im.social.places.insert.xml.
        /// </summary>
        internal static string im_social_places_insert {
            get {
                return ResourceManager.GetString("im_social_places_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.im.social.utente.attivita.insert.xml.
        /// </summary>
        internal static string im_social_utente_attivita_insert {
            get {
                return ResourceManager.GetString("im_social_utente_attivita_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.im.social.utente.attivita.list.xml.
        /// </summary>
        internal static string im_social_utente_attivita_list {
            get {
                return ResourceManager.GetString("im_social_utente_attivita_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.im.social.utente.element.username.pass.xml.
        /// </summary>
        internal static string im_social_utente_element_username_pass {
            get {
                return ResourceManager.GetString("im_social_utente_element_username_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.im.social.utente.list.bynumarticoli.xml.
        /// </summary>
        internal static string im_social_utente_list_top_autori {
            get {
                return ResourceManager.GetString("im_social_utente_list_top_autori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.social.votiutenti.im.element.xml.
        /// </summary>
        internal static string im_social_votiutenti_im_element {
            get {
                return ResourceManager.GetString("im_social_votiutenti_im_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.social.votiutenti.im.insert.xml.
        /// </summary>
        internal static string im_social_votiutenti_im_insert {
            get {
                return ResourceManager.GetString("im_social_votiutenti_im_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.im.viewstate.element_viewstate.xml.
        /// </summary>
        internal static string im_viewstate_element_viewstate {
            get {
                return ResourceManager.GetString("im_viewstate_element_viewstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.webpart.list_viewstate.xml.
        /// </summary>
        internal static string im_webpart_list_viewstate {
            get {
                return ResourceManager.GetString("im_webpart_list_viewstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tiin.
        /// </summary>
        internal static string tema {
            get {
                return ResourceManager.GetString("tema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SI.
        /// </summary>
        internal static string validazione {
            get {
                return ResourceManager.GetString("validazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to viewState.
        /// </summary>
        internal static string viewStateDir {
            get {
                return ResourceManager.GetString("viewStateDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dati.
        /// </summary>
        internal static string xmlDatiDir {
            get {
                return ResourceManager.GetString("xmlDatiDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xml.
        /// </summary>
        internal static string xmlDIR {
            get {
                return ResourceManager.GetString("xmlDIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmlOutput.
        /// </summary>
        internal static string xmlOutputDIR {
            get {
                return ResourceManager.GetString("xmlOutputDIR", resourceCulture);
            }
        }
    }
}
